INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
ERROR:root:Error Occurred while processing request: {'responseId': 'd712a54c-3481-41bc-b7ea-c55ff1e3bdc8-ee7586fb', 'queryResult': {'queryText': 'CBI', 'parameters': {'TestCasetopic': ['CBI']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['CBI'], 'TestCasetopic.original': ['CBI']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} , 

 Error: <traceback object at 0x7f970f9775c8>
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 13:14:29] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
ERROR:root:Error Occurred while processing request: {'responseId': 'a110d249-b318-4cff-909b-fb845ddfa298-ee7586fb', 'queryResult': {'queryText': 'TFR', 'parameters': {'TestCasetopic': ['TFR']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['TFR'], 'TestCasetopic.original': ['TFR']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} , 

 Error: <traceback object at 0x7fe6f106d608>
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 13:17:32] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
ERROR:flask.app:Exception on / [POST]
Traceback (most recent call last):
  File "app.py", line 30, in webhook
    intent = request['queryResult']['intent']['displayName']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
TypeError: 'Request' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 33, in webhook
    logging.error("Error Occurred while processing request: {0} , \n\n Error: {1}".format(str(request_), str(e.__traceback__()) ))
TypeError: 'traceback' object is not callable
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 13:19:18] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
DEBUG:root:Recieved Request with id = 7716a124-659e-418a-b3cc-4497376b0ed4-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': '7716a124-659e-418a-b3cc-4497376b0ed4-ee7586fb', 'queryResult': {'queryText': 'TFR', 'parameters': {'TestCasetopic': ['TFR']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['TFR'], 'TestCasetopic.original': ['TFR']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
ERROR:flask.app:Exception on / [POST]
Traceback (most recent call last):
  File "app.py", line 55, in webhook
    fulfilment = json.load(open(INTENTS_2_CHANNELS[intent].replace('/','')+'.json','r'))
FileNotFoundError: [Errno 2] No such file or directory: 'db9c38caTestCaseResults.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 76, in webhook
    logging.error("Error Occurred while processing request: {0} , \n\n Error: {1}".format(str(request_), str(e.__traceback__()) ))
TypeError: 'traceback' object is not callable
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 13:21:02] "POST / HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
DEBUG:root:Recieved Request with id = 1b881920-f65f-473e-b0d5-dcca6f0ff967-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': '1b881920-f65f-473e-b0d5-dcca6f0ff967-ee7586fb', 'queryResult': {'queryText': 'TFR', 'parameters': {'TestCasetopic': ['TFR']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['TFR'], 'TestCasetopic.original': ['TFR']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:Successfully fulfilled id 1b881920-f65f-473e-b0d5-dcca6f0ff967-ee7586fb with {'id': '1b881920-f65f-473e-b0d5-dcca6f0ff967-ee7586fb', 'data': {'id': '1b881920-f65f-473e-b0d5-dcca6f0ff967-ee7586fb', 'fulfillmentText': 'output from fullfilment test TCR: 0012020-11-13 13:22:33.873599'}} 
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 13:22:34] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
DEBUG:root:Recieved Request with id = 4275332b-6a89-4598-bb17-bb8a31544e1c-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': '4275332b-6a89-4598-bb17-bb8a31544e1c-ee7586fb', 'queryResult': {'queryText': 'show me test cases related to MTO', 'parameters': {'TestCasetopic': ['MTO']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'lifespanCount': 1, 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['MTO'], 'TestCasetopic.original': ['MTO']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:Successfully fulfilled id 4275332b-6a89-4598-bb17-bb8a31544e1c-ee7586fb with {'id': '4275332b-6a89-4598-bb17-bb8a31544e1c-ee7586fb', 'data': {'id': '4275332b-6a89-4598-bb17-bb8a31544e1c-ee7586fb', 'fulfillmentText': 'output from fullfilment test TCR: 0012020-11-13 13:25:21.317240'}} 
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 13:25:22] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
DEBUG:root:Recieved Request with id = e398310d-a336-4b06-92cc-f057afa6299b-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': 'e398310d-a336-4b06-92cc-f057afa6299b-ee7586fb', 'queryResult': {'queryText': 'Show me test cases related to CBI', 'parameters': {'TestCasetopic': ['CBI']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['CBI'], 'TestCasetopic.original': ['CBI']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:attempt: 1
DEBUG:root:attempt: 2
DEBUG:root:attempt: 3
DEBUG:root:attempt: 4
ERROR:root:FFM Unsuccessful for id e398310d-a336-4b06-92cc-f057afa6299b-ee7586fb
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 20:36:40] "POST / HTTP/1.1" 200 -
DEBUG:root:Recieved Request with id = af12fdc5-fe36-4608-ab8a-18f43064dfc4-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': 'af12fdc5-fe36-4608-ab8a-18f43064dfc4-ee7586fb', 'queryResult': {'queryText': 'show me test cases related to CBI', 'parameters': {'TestCasetopic': ['CBI']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['CBI'], 'TestCasetopic.original': ['CBI']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:attempt: 1
DEBUG:root:attempt: 2
DEBUG:root:attempt: 3
DEBUG:root:attempt: 4
ERROR:root:FFM Unsuccessful for id af12fdc5-fe36-4608-ab8a-18f43064dfc4-ee7586fb
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 20:38:42] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 20:43:27] "GET /ads HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 20:43:28] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
DEBUG:root:Recieved Request with id = d755cc69-a8e5-4c34-b5e4-0e30054eda24-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': 'd755cc69-a8e5-4c34-b5e4-0e30054eda24-ee7586fb', 'queryResult': {'queryText': 'show me test cases related to CBI', 'parameters': {'TestCasetopic': ['CBI']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['CBI'], 'TestCasetopic.original': ['CBI']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:attempt: 1
DEBUG:root:attempt: 2
DEBUG:root:attempt: 3
DEBUG:root:attempt: 4
ERROR:root:FFM Unsuccessful for id d755cc69-a8e5-4c34-b5e4-0e30054eda24-ee7586fb
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 21:07:23] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
DEBUG:root:Recieved Request with id = 402c2580-b186-48bc-a61d-b329fa087dd8-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': '402c2580-b186-48bc-a61d-b329fa087dd8-ee7586fb', 'queryResult': {'queryText': 'show me test cases related to CBI', 'parameters': {'TestCasetopic': ['CBI']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['CBI'], 'TestCasetopic.original': ['CBI']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:Successfully fulfilled id 402c2580-b186-48bc-a61d-b329fa087dd8-ee7586fb with {'data': {'fulfillmentText': 'output from fullfilment test TCR: 0012020-11-13 21:24:54.965126', 'id': '402c2580-b186-48bc-a61d-b329fa087dd8-ee7586fb'}, 'id': '402c2580-b186-48bc-a61d-b329fa087dd8-ee7586fb'} 
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 21:24:55] "POST / HTTP/1.1" 200 -
DEBUG:root:Recieved Request with id = 969a4f9c-9d6d-4a4f-a711-0c2b8b52d762-ee7586fb , intent = Reterive Test Cases
DEBUG:root:Successfully published the request {'responseId': '969a4f9c-9d6d-4a4f-a711-0c2b8b52d762-ee7586fb', 'queryResult': {'queryText': 'TFR', 'parameters': {'TestCasetopic': ['TFR']}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'text': {'text': ['']}}], 'outputContexts': [{'name': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'TestCasetopic': ['TFR'], 'TestCasetopic.original': ['TFR']}}], 'intent': {'name': 'projects/sqebot-ikcd/agent/intents/189078af-aa0c-4dfe-9460-950c47bf1fa1', 'displayName': 'Reterive Test Cases'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'source': 'DIALOGFLOW_CONSOLE', 'payload': {}}, 'session': 'projects/sqebot-ikcd/agent/sessions/d58ef604-b80f-9a10-4f46-fe3ebb2397f2'} 

to the channel: db9c38ca/TestCaseResults
DEBUG:root:attempt: 0
DEBUG:root:Successfully fulfilled id 969a4f9c-9d6d-4a4f-a711-0c2b8b52d762-ee7586fb with {'data': {'fulfillmentText': 'output from fullfilment test TCR: 0012020-11-13 21:25:46.282865', 'id': '969a4f9c-9d6d-4a4f-a711-0c2b8b52d762-ee7586fb'}, 'id': '969a4f9c-9d6d-4a4f-a711-0c2b8b52d762-ee7586fb'} 
INFO:werkzeug:127.0.0.1 - - [13/Nov/2020 21:25:47] "POST / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4040
DEBUG:urllib3.connectionpool:http://localhost:4040 "GET /api/tunnels HTTP/1.1" 200 779
